export const az = {
  meta: {
    title: "Alluminaty, Where Your Alumni Network Lives",
    description:
      "Alluminaty is the modern alumni network your institution owns. Keep graduates reachable, connect students with mentors and jobs, and fund scholarships.",
  },
  hero: {
    titleLine1: "Where your",
    titleLine2: "alumni network lives.",
    titleAccent: "alumni network lives.",
    body: "Alluminaty turns every batch into a living network your institution owns. Alumni stay reachable, students gain mentors and jobs, and the community keeps giving back for decades, all under your brand.",
    primaryLabel: "Get A Demo",
    primaryHref: "/book-a-demo",
    secondaryLabel: "See it live",
    secondaryHref: "https://nnawca.vercel.app",
    builtBy: "Built by Timewheel",
    members: [
      { name: "Pranav Kadoo", meta: "Batch 2006–13 · Shiwalik House" },
      { name: "Ritika Deshmukh", meta: "Batch 2012–19 · Nilgiri House" },
      { name: "Anil Chakraborty", meta: "Batch 1998–05 · Aravali House" },
    ],
  },
  stats: [
    { value: "500+", label: "Verified alumni" },
    { value: "18", label: "Countries connected" },
    { value: "10", label: "Houses & batches" },
    { value: "1", label: "Network you own" },
  ],
  ticker: [
    "Verified Directory",
    "Discover by Batch & City",
    "Professional Profiles",
    "Mentorship",
    "Jobs & Referrals",
    "Chapters & Communities",
    "Events & Reunions",
    "Lifelong Connections",
  ],
  problem: {
    number: "01",
    label: "THE CHALLENGE",
    title: "Your alumni are your biggest asset, and most have slipped away.",
    body: "Every batch leaves as a lifelong supporter, a mentor, a donor, a future recruiter. Then contact fades, and the relationship your institution spent years building quietly disappears.",
    items: [
      {
        name: "You lose touch at graduation",
        desc: "The students you shaped for years walk out, and within a batch or two most are unreachable.",
      },
      {
        name: "Your records go stale",
        desc: "Alumni contacts scatter across old spreadsheets and inboxes nobody can search or trust.",
      },
      {
        name: "Students miss the network",
        desc: "Current students can't reach the alumni who could offer a mentor, a referral or a first job.",
      },
      {
        name: "Engagement rests on a few",
        desc: "Reunions, giving and outreach ride on a handful of volunteers and group chats that fade.",
      },
    ],
  },
  solution: {
    number: "02",
    label: "THE SOLUTION",
    title: "One connected network your institution owns.",
    body: "Alluminaty brings your alumni into one verified community you own, so graduates stay reachable, students stay supported, and the network keeps giving back for decades.",
    items: [
      "A verified directory you own",
      "Your institution's branded home",
      "Alumni reachable by batch, city & company",
      "Mentors & jobs for your students",
      "Scholarships, giving & fundraising",
      "Events & reunions that run themselves",
    ],
  },
  beforeAfter: {
    number: "03",
    label: "BEFORE / AFTER",
    title: "From a scattered batch\nto a network you own.",
    titleAccent: "network you own.",
    body: "The bond was always there. Alluminaty keeps it reachable, and working for your institution.",
    beforeTitle: "Before Alluminaty",
    afterTitle: "With Alluminaty",
    before: [
      "Graduates unreachable within a few batches",
      "Alumni records buried in stale spreadsheets",
      "Reunions and giving run by a few volunteers",
      "Students cut off from the alumni who could help",
    ],
    after: [
      "A verified alumni directory you own",
      "Alumni found by batch, city, company or profession",
      "Events, chapters and giving in one branded home",
      "Mentors, referrals and jobs for your students",
    ],
    stats: [
      { value: "500+", label: "alumni reconnected" },
      { value: "18", label: "countries in one network" },
    ],
  },
  features: {
    number: "04",
    label: "WHAT'S INSIDE",
    title: "Everything it takes to keep your alumni close.",
    body: "Six connected experiences your alumni will love, and that quietly return mentors, donors and recruiters to your institution.",
    items: [
      {
        icon: "users",
        name: "Verified Directory",
        desc: "A searchable directory of your real alumni, verified against your records, so the network you own stays trusted and reachable.",
        bullets: [
          "Verified members only",
          "Search by batch, city, company or profession",
          "Highlighted profiles for premium members",
        ],
      },
      {
        icon: "message",
        name: "Community & Feed",
        desc: "A branded social feed that keeps your alumni talking long after campus, with your institution at the center of it.",
        bullets: [
          "Activity feed & posts",
          "Polls, comments & reactions",
          "Direct messaging & groups",
        ],
      },
      {
        icon: "calendar",
        name: "Events & Reunions",
        desc: "Founders' day, reunions and city meetups that alumni discover, RSVP and even host themselves, with far less work for your team.",
        bullets: [
          "Event listings & RSVP",
          "Alumni host their own events",
          "Reminders & personal calendar",
        ],
      },
      {
        icon: "store",
        name: "Jobs & Opportunities",
        desc: "Alumni share jobs, referrals and business opportunities, opening doors for each other and for your current students.",
        bullets: [
          "Alumni job board & referrals",
          "Business & startup directory",
          "Placement support for students",
        ],
      },
      {
        icon: "heart",
        name: "Mentorship & Giving Back",
        desc: "Alumni mentor the next batch and fund scholarships and welfare, turning goodwill into real support for your institution.",
        bullets: [
          "Mentor & mentee matching",
          "Scholarship & welfare drives",
          "Career support for students",
        ],
      },
      {
        icon: "shield",
        name: "Chapters & Membership",
        desc: "City and interest chapters, and membership tiers that fund the network and keep it alive without leaning on your office.",
        bullets: [
          "City & interest chapters",
          "Free to lifetime tiers",
          "Verified member badges",
        ],
      },
    ],
  },
  process: {
    number: "05",
    label: "HOW IT WORKS",
    title: "From launch\nto a network that runs itself.",
    body: "Five simple moves take a scattered batch and turn it into a self-sustaining community your institution can be proud of.",
    steps: [
      {
        name: "Launch & verify",
        stop: "VERIFY",
        desc: "Alumni sign up with their real batch details, verified against your institution's records.",
      },
      {
        name: "They find their people",
        stop: "FIND",
        desc: "Members search by batch, city, company or profession, and reconnect in a tap.",
      },
      {
        name: "They build a profile",
        stop: "PROFILE",
        desc: "A professional alumni profile that shows where they studied and where they are now.",
      },
      {
        name: "The network comes alive",
        stop: "CONNECT",
        desc: "Chapters, events, mentorship and opportunities bring your alumni back together.",
      },
      {
        name: "It sustains itself",
        stop: "SUSTAIN",
        desc: "Chapters, membership and giving back keep it running for generations, not just one reunion.",
      },
    ],
  },
  pricing: {
    number: "06",
    label: "MEMBERSHIP",
    title: "Belong, and give back.",
    body: "Every tier keeps the network alive and funds scholarships, welfare drives, events and mentorship. Each institution chooses what its alumni pay.",
    footnote: "Secured by Razorpay · Non-refundable contributions · Each institution sets its own tiers",
    plans: [
      {
        name: "Member",
        tagline: "Stay connected forever",
        price: "₹0",
        unit: "free",
        highlight: false,
        features: [
          "Directory & profiles",
          "Join events & chapters",
          "Post, comment & poll",
          "Voting rights (verified + 30 days)",
        ],
      },
      {
        name: "Associate",
        tagline: "Give back & get more",
        price: "₹499",
        unit: "/ year",
        highlight: true,
        features: [
          "Full, uncapped feed",
          "Reduced ads",
          "Post jobs & referrals",
          "Video calling · 30 min/call",
          "1 GB gallery storage",
          "Verified Associate badge",
        ],
      },
      {
        name: "Premium",
        tagline: "Lead the network",
        price: "₹999",
        unit: "/ year",
        highlight: false,
        features: [
          "Everything in Associate",
          "Ad-free feed",
          "Highlighted profile",
          "List your business",
          "Video calling · 60 min/call",
          "Earlier event invitations",
        ],
      },
      {
        name: "Life Member",
        tagline: "A lifetime of belonging",
        price: "₹9,999",
        unit: "one-time",
        highlight: false,
        features: [
          "Everything in Premium, forever",
          "Never renews or expires",
          "Permanent Life Member badge",
          "Video calling · 90 min/call",
          "Eligible for Committee invitation",
        ],
      },
    ],
  },
  matrix: {
    heading: "Benefit Matrix",
    note: "Voting in decisions is open to any verified member with 30+ days active, regardless of paid tier.",
    columns: ["Benefit", "Member", "Associate", "Premium", "Life"],
    rows: [
      { name: "Alumni feed", values: ["Preview", "Full", "Full", "Full"] },
      { name: "Feed ads", values: ["Standard", "Reduced", "Ad-free", "Ad-free"] },
      { name: "Video calling", values: ["Pass", "30 min", "60 min", "90 min"] },
      { name: "Gallery storage", values: ["200 MB", "1 GB", "5 GB", "10 GB"] },
      { name: "Highlighted profile", values: ["–", "–", "Yes", "Yes"] },
      { name: "Business listing", values: ["–", "–", "Yes", "Yes"] },
      { name: "Committee eligibility", values: ["–", "–", "–", "Yes"] },
    ],
  },
  capabilities: {
    number: "07",
    label: "WHAT TIMEWHEEL BUILT",
    title: "A complete platform,\nend to end.",
    body: "Timewheel designed, built and shipped Alluminaty as a complete social product, from strategy to production, so your institution gets a finished network, not a project.",
    items: [
      { icon: "compass", label: "Product Strategy" },
      { icon: "pen", label: "UX / UI Design" },
      { icon: "layout", label: "Design System" },
      { icon: "code", label: "Frontend Development" },
      { icon: "server", label: "Backend & APIs" },
      { icon: "database", label: "Database & Storage" },
      { icon: "shield", label: "Auth & Verification" },
      { icon: "wallet", label: "Payments (Razorpay)" },
      { icon: "message", label: "Feeds, Groups & Events" },
    ],
  },
  testimonials: {
    number: "08",
    label: "FROM THE NETWORK",
    title: "Loved by alumni, trusted by institutions.",
    body: "It started as a directory. It became a community the whole institution leans on.",
    items: [
      {
        quote:
          "Alluminaty turned a scattered batch into a living network, the one place where every graduate finds their way home.",
        name: "Pranav Kadoo",
        role: "Alumnus · Batch 2006–13, Shiwalik House",
        initials: "PK",
      },
      {
        quote:
          "For the first time we have one verified place to reach every batch. Our alumni cell runs on it now, from reunions to giving.",
        name: "Ritika Deshmukh",
        role: "Head, Alumni Relations",
        initials: "RD",
      },
      {
        quote:
          "I found a mentor two batches above me, and a job through a referral, all inside the network.",
        name: "Anil Chakraborty",
        role: "Alumnus & Chapter Lead",
        initials: "AC",
      },
    ],
  },
  faq: {
    number: "09",
    label: "FAQ",
    title: "Questions, answered.",
    items: [
      {
        q: "Who is Alluminaty for?",
        a: "Schools, colleges, universities and coaching networks that want a modern, lifelong alumni community they own, directory, professional profiles, chapters, events, mentorship and giving in one branded product.",
      },
      {
        q: "Does our institution own the network?",
        a: "Yes. The directory, the data and the community are yours, under your institution's brand. Alluminaty is the platform, your alumni are your network, and membership is verified against your real records.",
      },
      {
        q: "How much work is it for our team?",
        a: "Little. Alumni self-verify, host their own events and chapters, and membership sustains the network, so your office guides the community rather than running it day to day.",
      },
      {
        q: "What does it return to the institution?",
        a: "Reachable alumni, mentors and recruiters for your students, and funding for scholarships and welfare, with governance, reporting and audits for full transparency.",
      },
      {
        q: "Can we run events, chapters and committees on it?",
        a: "Yes. Alumni discover, RSVP and host events and reunions, and city or interest chapters are configured with elected and advisory roles for the members who keep the community alive.",
      },
    ],
  },
  final: {
    title: "Bring your alumni home.",
    body: "Alluminaty keeps every graduate reachable and giving back, under your institution's brand. It is one example of what Timewheel can build, and yours could be next.",
    primaryLabel: "Get A Demo",
    primaryHref: "/book-a-demo",
    secondaryLabel: "Explore Timewheel",
    secondaryHref: "/",
  },
};
