export const shots = {
  booking16x9: {
    src: "/products/bas-booking-16x9.png",
    width: 1440,
    height: 810,
  },
  bookingFlow: {
    src: "/products/bas-booking-flow.png",
    width: 1440,
    height: 810,
  },
  dashboardPortrait: {
    src: "/products/bas-dashboard-portrait.png",
    width: 722,
    height: 866,
  },
  dashboard16x10: {
    src: "/products/bas-dashboard-16x10.png",
    width: 722,
    height: 451,
  },
  heroBanner: {
    src: "https://company-assets.bookasloth.in/images/banner/hero-book-a-sloth.png",
    width: 480,
    height: 550,
  },
};

export const bas = {
  meta: {
    title: "Book A Sloth — Built by Timewheel",
    description:
      "Explore Book A Sloth, a booking and scheduling platform built by Timewheel. See how we design, develop and automate digital products for businesses.",
  },
  nav: {
    links: [
      { label: "Work", href: "#product" },
      { label: "Services", href: "/digital-marketing" },
      { label: "About", href: "/about" },
    ],
  },
  liveUrl: "https://bookasloth.com",
  hero: {
    titleLine1: "Everything You Need",
    titleLine2: "to Manage Bookings.",
    titleAccent: "Manage Bookings.",
    body: "Book A Sloth helps businesses manage appointments, customers, availability, payments and automated communication — all from one simple platform.",
    primary: "Visit Site",
    secondary: "Get Started",
    shotUrl: "bookasloth.com",
    shot: "dashboard16x10",
    shotAlt: "Book A Sloth marketing banner",
    builtBy: "Built by Timewheel",
  },
  intro: {
    number: "01",
    label: "THE PRODUCT",
    title: "Everything needed to manage bookings.",
    body: "Book A Sloth connects booking, scheduling, customers and automation in one product.",
    shotAlt: "Book A Sloth booking page",
    shotCaption: "CUSTOMER EXPERIENCE",
    shotDesc: "Simple booking from the customer's side.",
  },
  problem: {
    number: "02",
    // label: "THE CHALLENGE",
    title: "Booking shouldn't\nbe manual.",
    body: "Running a service business always meant juggling bookings across calls, chats, and a scattered set of tools.",
    fact: "The hours spent scheduling could be a full-time job on their own.",
    items: [
      {
        name: "Manual bookings",
        desc: "Appointments arrive over calls, messages and walk-ins — never in one place.",
      },
      {
        name: "Back-and-forth communication",
        desc: "Confirming, rescheduling and reminding means endless messages.",
      },
      {
        name: "Scattered customer information",
        desc: "Client details live across chats, notebooks and spreadsheets.",
      },
      {
        name: "Missed appointments",
        desc: "Without reminders, no-shows quietly eat into the day.",
      },
      {
        name: "Repetitive follow-ups",
        desc: "The same messages get typed and sent again and again.",
      },
    ],
  },
  solution: {
    number: "03",
    label: "THE SOLUTION",
    title: "One connected\nbooking experience.",
    body: "Everything that used to live in separate places now lives in one calm, connected product.",
    items: [
      "Simple booking",
      "Business dashboard",
      "Automated communication",
      "Centralized management",
    ],
  },
  showcase: {
    number: "04",
    label: "THE PRODUCT",
    title: "Built as one product.",
    body: "Three connected experiences — for customers, for the business, and for the hours of work that used to go into managing it.",
    shots: [
      {
        id: "dashboard",
        shot: "dashboard16x10",
        label: "BUSINESS DASHBOARD",
        desc: "Manage bookings, customers and schedules from one workspace.",
      },
      {
        id: "customer",
        shot: "bookingFlow",
        label: "CUSTOMER EXPERIENCE",
        desc: "A simple booking experience designed for customers.",
      },
      {
        id: "automation",
        shot: null,
        label: "AUTOMATION",
        desc: "Automate confirmations, reminders and follow-ups.",
      },
    ],
  },
  automation: {
    number: "05",
    label: "AUTOMATION",
    title: "Automate the work\nbehind every booking.",
    body: "Each step of a booking triggers the next — automatically.",
    steps: [
      "Booking",
      "Confirmation",
      "Reminder",
      "Appointment",
      "Follow-up",
    ],
  },
  beforeAfter: {
    number: "06",
    label: "BEFORE / AFTER",
    title: "From manual juggling\nto automatic flow.",
    titleAccent: "automatic flow.",
    body: "Every step of the booking lifecycle used to demand attention. Now it runs itself.",
    beforeTitle: "Before Book A Sloth",
    afterTitle: "With Book A Sloth",
    before: [
      "Manual bookings",
      "Multiple tools",
      "Manual follow-ups",
      "Scattered information",
    ],
    after: [
      "Online booking",
      "Centralized dashboard",
      "Automated communication",
      "Connected customer data",
    ],
    stats: [
      { value: "12+ hrs", label: "saved every week" },
      { value: "−60%", label: "fewer no-shows" },
    ],
  },
  capabilities: {
    number: "07",
    label: "WHAT WE BUILT",
    title: "From idea\nto production.",
    body: "Timewheel designed and built Book A Sloth as a complete digital product.",
    items: [
      { icon: "compass", label: "Product Strategy" },
      { icon: "pen", label: "UX / UI Design" },
      { icon: "code", label: "Frontend Development" },
      { icon: "server", label: "Backend Development" },
      { icon: "database", label: "Database & APIs" },
      { icon: "layout", label: "Dashboard Development" },
      { icon: "workflow", label: "Automation" },
      { icon: "mail", label: "Email Workflows" },
      { icon: "monitor", label: "Responsive Experience" },
      { icon: "package", label: "Production Architecture" },
    ],
  },
  transition: {
    number: "08",
    label: "ONE PRODUCT IS ONLY THE BEGINNING.",
    title: "What could we build\nfor your business?",
    body: "Book A Sloth is one example of how Timewheel turns business ideas and workflows into real digital products.",
    examples: [
      "Booking Platforms",
      "SaaS Products",
      "Business Dashboards",
      "Customer Portals",
      "Marketplaces",
      "Automation Systems",
    ],
  },
  process: {
    number: "09",
    label: "HOW TIMEWHEEL BUILDS",
    title: "From idea\nto launch.",
    body: "A simple, proven process — the same one that took Book A Sloth from an idea to a shipping product.",
    steps: [
      { name: "Discover", desc: "The business, the users, the workflow." },
      { name: "Design", desc: "The product and every screen in it." },
      { name: "Build", desc: "The product, backend and integrations." },
      { name: "Automate", desc: "The repetitive work and communication." },
      { name: "Launch", desc: "Ship, measure, improve, and scale." },
    ],
  },
  steps: {
    number: "10",
    // label: "HOW IT WORKS",
    title: "One link. Get booked, get paid, get your time back.",
    body: "Six simple steps between you and getting booked, getting paid over UPI, and getting your time back.",
    steps: [
      {
        name: "Create your page",
        stop: "PAGE",
        desc: "Build a professional booking profile for your business.",
      },
      {
        name: "Add your services",
        stop: "SERVICES",
        desc: "Set service duration, pricing, availability, and booking rules.",
      },
      {
        name: "Share your link",
        stop: "SHARE",
        desc: "Add it to WhatsApp, Instagram, Google, or your website.",
      },
      {
        name: "Receive bookings",
        stop: "BOOK",
        desc: "Customers book from your live availability without back-and-forth messages.",
      },
      {
        name: "Get paid",
        stop: "PAY",
        desc: "Collect full payments or deposits during the booking process.",
      },
      {
        name: "Manage everything",
        stop: "DONE",
        desc: "Track bookings, customers, payments, staff, and schedules from one dashboard.",
      },
    ],
  },
  features: {
    number: "11",
    label: "WHAT'S INSIDE",
    title: "Everything needed to manage bookings.",
    categories: [
      {
        id: "calendar",
        tab: "Calendar",
        icon: "calendar",
        color: "#FE5100",
        module: "SCHEDULING",
        title: "Bookings, availability and calendars in one place",
        body: "Manage schedules, resources, breaks and recurring appointments without the spreadsheet.",
        items: [
          "Unlimited calendars",
          "Team availability",
          "Recurring schedules",
          "Buffer & break rules",
          "Resource booking",
          "Custom availability",
        ],
      },
      {
        id: "customers",
        tab: "Customers",
        icon: "users",
        color: "#2563EB",
        module: "CUSTOMER DATA",
        title: "One profile for every customer",
        body: "Every customer's history, notes and preferences live in a single clean profile.",
        items: [
          "Customer profiles",
          "Booking history",
          "Notes & tags",
          "Preferences",
          "Favorite services",
          "Communication log",
        ],
      },
      {
        id: "payments",
        tab: "Payments",
        icon: "wallet",
        color: "#16A34A",
        module: "PAYMENTS",
        title: "Collect payments without the chase",
        body: "Deposits, prepayments and invoices connect to every booking.",
        items: [
          "Online payments",
          "Deposits & advances",
          "Invoices",
          "Receipts",
          "Refund handling",
          "Payment links",
        ],
      },
      {
        id: "automation",
        tab: "Automation",
        icon: "blocks",
        color: "#8B5CF6",
        module: "AUTOMATION",
        title: "Let the software do the follow-up",
        body: "Confirmations, reminders and follow-ups send themselves.",
        items: [
          "Booking confirmations",
          "Reminders",
          "No-show follow-ups",
          "Reschedule prompts",
          "Custom templates",
          "Scheduled messages",
        ],
      },
      {
        id: "security",
        tab: "Security",
        icon: "shield",
        color: "#0EA5E9",
        module: "SECURITY",
        title: "Built on enterprise-grade security",
        body: "Permissions, backups and audit trails keep business data safe.",
        items: [
          "Role-based access",
          "Audit logs",
          "Encrypted storage",
          "Automated backups",
          "Data export",
          "Secure API",
        ],
      },
      {
        id: "support",
        tab: "Support",
        icon: "heart",
        color: "#EC4899",
        module: "SUPPORT",
        title: "A product that feels cared for",
        body: "Real humans, fast responses, and a product that keeps getting better.",
        items: [
          "Email support",
          "WhatsApp support",
          "Help center",
          "Onboarding calls",
          "Changelog",
          "Feature requests",
        ],
      },
    ],
  },
  integrations: {
    number: "12",
    label: "CONNECTIONS",
    title: "Plays well with your stack.",
    body: "Book A Sloth connects with the tools your business already uses.",
    note: "More integrations ship every month.",
    items: [
      { icon: "wa", name: "WhatsApp" },
      { icon: "gcal", name: "Google Calendar" },
      { icon: "meet", name: "Google Meet" },
      { icon: "razorpay", name: "Razorpay" },
      { icon: "upi", name: "UPI" },
      { icon: "sso", name: "Single Sign-On" },
    ],
  },
  testimonials: {
    number: "13",
    label: "REVIEWS",
    rating: "4.9",
    reviews: "180+",
    badge: "Excellent",
    title: "Teams that run on Book A Sloth.",
    body: "Service businesses moved off manual bookings and never looked back.",
    items: [
      {
        quote: "Our front desk finally stopped double-booking. Bookings just land on the calendar.",
        name: "Priya Sharma",
        role: "Salon Owner",
        initials: "PS",
      },
      {
        quote: "Reminders alone cut our no-shows by half within a month.",
        name: "Rahul Mehta",
        role: "Clinic Manager",
        initials: "RM",
      },
      {
        quote: "It replaced three tools. The team picked it up in an afternoon.",
        name: "Ananya Iyer",
        role: "Studio Founder",
        initials: "AI",
      },
    ],
  },
  faq: {
    number: "14",
    label: "FAQ",
    title: "Questions, answered.",
    items: [
      {
        q: "Is there a free plan?",
        a: "Yes — Book A Sloth starts free and grows with you. You only pay for what you actually use.",
      },
      {
        q: "Can I migrate my existing bookings?",
        a: "Yes. We help you import customers, services and upcoming appointments so you don't start from zero.",
      },
      {
        q: "Does it work on my phone?",
        a: "Book A Sloth is fully responsive, so your team can manage bookings from any device.",
      },
      {
        q: "What happens after I sign up?",
        a: "You get a guided onboarding, and real humans on support if you get stuck.",
      },
    ],
  },
  pricing: {
    number: "15",
    label: "PLANS",
    title: "Simple, honest pricing.",
    body: "Start free. Upgrade when your bookings are worth it.",
    footnote: "No setup fees. Cancel anytime.",
    plans: [
      {
        name: "Starter",
        tagline: "For getting your first bookings",
        highlight: false,
        features: [
          "1 calendar",
          "Booking page",
          "Email reminders",
          "Basic reporting",
        ],
      },
      {
        name: "Growth",
        tagline: "For growing service businesses",
        highlight: true,
        features: [
          "Unlimited calendars",
          "WhatsApp reminders",
          "Payments & deposits",
          "Automation workflows",
          "Priority support",
        ],
      },
      {
        name: "Business",
        tagline: "For teams, agencies & enterprises",
        highlight: false,
        features: [
          "Everything in Growth",
          "Role-based access",
          "SSO & audit logs",
          "API & webhooks",
          "Dedicated support",
        ],
      },
    ],
  },
  walkthrough: {
    number: "16",
    label: "WALKTHROUGH",
    title: "How a booking flows\nthrough Book A Sloth.",
    body: "From first click to follow-up — every step is handled.",
    steps: [
      {
        name: "Check availability",
        desc: "The customer opens the booking page and sees what's open.",
      },
      {
        name: "Pick a slot",
        desc: "They choose a service, a time and a team member.",
      },
      {
        name: "Confirm",
        desc: "Confirmation goes out instantly on email and WhatsApp.",
      },
      {
        name: "Remind",
        desc: "Automated reminders run before the appointment.",
      },
      {
        name: "Follow up",
        desc: "After the visit, a gentle follow-up goes out.",
      },
    ],
    services: [
      { name: "Google Calendar sync", price: "Included" },
      { name: "WhatsApp reminders", price: "Growth+" },
      { name: "Payments & deposits", price: "Growth+" },
    ],
  },
  final: {
    title: "Have an idea?",
    big: "Let's build it.",
    body: "Book A Sloth is one example of what Timewheel can build. Your product could be next.",
    primary: "Start a Project",
    secondary: "Explore Timewheel",
  },
};